### ISSUE TITLE
Experences in non-Wifi connections and different carriers

### ISSUE THREAD

**Issue by timmurphree** [mateagar/Motion-JPEG-Image-View-for-iOS#2]
Hello, 
I have a Phonegap-based app that attempts to stream Motion JPEG, from Axis IP cameras,  to iPhone, and have various success. 

These results are all prior to iOS6: 
- AT&T, 3G / 4G connection  - app would not work - not even one frame. 
- AT&T, Wifi - app worked fine. 
- Verizon,4G connection - app would "work", maybe a frame every few seconds. Poor performance. 
- Verizon, Wifi - app worked fine. 

Now with iOS6, as everyone knows by now, MJPEG is broken. So, we are looking to develop a native iPhone app, using this alternative viewer, and would like a bit more information. 

I understand this does work with iPhone 5 / iOS6, but under what network or connection conditions? Can anyone share their results under AT&T, Verizon, with 3G / 4G / LTE? 

Also, I'm making an assumption here, based on what I have read, this viewer was developed and tested with Axis IP webcams. Can you share which model(s)? 

I looked at the code, and it appears it's using the Axis HTTP interface to simply go to the Video stream, which is easy to understand. Is there any other advice and guidance for Axis webcams? 

Thanks in advance, Tim

**Comment by mateagar** [comment]
Hi Tim,

This project is network agnostic - it simply takes an HTTP stream and parses through the data to pull out JPEG image frames, displaying each as they arrive. We use this in our application and have customers who have used over 3G connections in many countries and on many carriers. I suppose it is possible for carriers to block data, but I'm guessing this is fairly rare. I have had success with AT&T 3G prior to iOS6 and LTE on iOS6 with an iPhone 5. 

MJPEG is not a high-performance streaming protocol because there is no interframe compression (as you would get with H-264, for example). As a result, it is not surprising to see video slow to a few frames per second (or less, if the network connection is poor), and therefore I believe you will have a much better experience on a WiFi connection as compared with cellular.

For what it's worth, we are using an Axis M1011-W camera here in the office. No special configuration - we have tested with various kinds of encryption and password protection and it all works fine.

Cheers,

Matt

On Oct 18, 2012, at 10:04 AM, timmurphree notifications@github.com wrote:

Hello, 
I have a Phonegap-based app that attempts to stream Motion JPEG, from Axis IP cameras, to iPhone, and have various success.

These results are all prior to iOS6:

AT&T, 3G / 4G connection - app would not work - not even one frame.
AT&T, Wifi - app worked fine.
Verizon,4G connection - app would "work", maybe a frame every few seconds. Poor performance.
Verizon, Wifi - app worked fine.
Now with iOS6, as everyone knows by now, MJPEG is broken. So, we are looking to develop a native iPhone app, using this alternative viewer, and would like a bit more information.

I understand this does work with iPhone 5 / iOS6, but under what network or connection conditions? Can anyone share their results under AT&T, Verizon, with 3G / 4G / LTE?

Also, I'm making an assumption here, based on what I have read, this viewer was developed and tested with Axis IP webcams. Can you share which model(s)?

I looked at the code, and it appears it's using the Axis HTTP interface to simply go to the Video stream, which is easy to understand. Is there any other advice and guidance for Axis webcams?

Thanks in advance, Tim
